name: Build

on:
  push:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: asdf-vm/actions/install@v1
      - run: spago -x spago.example.dhall build
      - run: spago -x spago.test.dhall test
      - run: for example in $(ls example); do spago -x spago.example.dhall run -m Example.${example%.*} -p example/$example; done
